INSERT INTO Cities VALUES(null,'Агдам');
INSERT INTO Cities VALUES(null,'Агдере');
INSERT INTO Cities VALUES(null,'Агдаш');
INSERT INTO Cities VALUES(null,'Агджабеди');
INSERT INTO Cities VALUES(null,'Аджигабул');
INSERT INTO Cities VALUES(null,'Агстафа (Акстафа)');
INSERT INTO Cities VALUES(null,'Астара');
INSERT INTO Cities VALUES(null,'Ахсу');
INSERT INTO Cities VALUES(null,'Бабек');
INSERT INTO Cities VALUES(null,'Баку');
INSERT INTO Cities VALUES(null,'Барда');
INSERT INTO Cities VALUES(null,'Бейлаган');
INSERT INTO Cities VALUES(null,'Белакен (Белоканы)');
INSERT INTO Cities VALUES(null,'Билясувар');
INSERT INTO Cities VALUES(null,'Габала');
INSERT INTO Cities VALUES(null,'Газах (Казах)');
INSERT INTO Cities VALUES(null,'Гах (Кахи)');
INSERT INTO Cities VALUES(null,'Гёйчай (Геокчай)');
INSERT INTO Cities VALUES(null,'Геранбой');
INSERT INTO Cities VALUES(null,'Гёйгёль');
INSERT INTO Cities VALUES(null,'Гёйтепе');
INSERT INTO Cities VALUES(null,'Гобустан');
INSERT INTO Cities VALUES(null,'Говлар');
INSERT INTO Cities VALUES(null,'Горадиз');
INSERT INTO Cities VALUES(null,'Губа (Куба)');
INSERT INTO Cities VALUES(null,'Губадлы (Кубатлы)');
INSERT INTO Cities VALUES(null,'Гусар (Кусары)');
INSERT INTO Cities VALUES(null,'Гянджа');
INSERT INTO Cities VALUES(null,'Далимамедли');
INSERT INTO Cities VALUES(null,'Дашкесан');
INSERT INTO Cities VALUES(null,'Джалилабад');
INSERT INTO Cities VALUES(null,'Джебраил');
INSERT INTO Cities VALUES(null,'Джульфа');
INSERT INTO Cities VALUES(null,'Евлах');
INSERT INTO Cities VALUES(null,'Загатала (Закаталы)');
INSERT INTO Cities VALUES(null,'Зангелан');
INSERT INTO Cities VALUES(null,'Зердаб');
INSERT INTO Cities VALUES(null,'Имишли');
INSERT INTO Cities VALUES(null,'Исмаиллы');
INSERT INTO Cities VALUES(null,'Кедабек');
INSERT INTO Cities VALUES(null,'Кельбаджар');
INSERT INTO Cities VALUES(null,'Кюрдамир');
INSERT INTO Cities VALUES(null,'Лачин');
INSERT INTO Cities VALUES(null,'Ленкорань');
INSERT INTO Cities VALUES(null,'Лерик');
INSERT INTO Cities VALUES(null,'Лиман');
INSERT INTO Cities VALUES(null,'Масаллы');
INSERT INTO Cities VALUES(null,'Мингечевир (Мингечаур)');
INSERT INTO Cities VALUES(null,'Нафталан');
INSERT INTO Cities VALUES(null,'Нахчыван (Нахичевань)');
INSERT INTO Cities VALUES(null,'Нефтечала');
INSERT INTO Cities VALUES(null,'Огуз');
INSERT INTO Cities VALUES(null,'Ордубад');
INSERT INTO Cities VALUES(null,'Саатлы');
INSERT INTO Cities VALUES(null,'Сабирабад');
INSERT INTO Cities VALUES(null,'Сальян (Сальяны)');
INSERT INTO Cities VALUES(null,'Самух');
INSERT INTO Cities VALUES(null,'Сиазань');
INSERT INTO Cities VALUES(null,'Сумгайыт (Сумгаит)');
INSERT INTO Cities VALUES(null,'Товуз');
INSERT INTO Cities VALUES(null,'Тертер');
INSERT INTO Cities VALUES(null,'Уджары');
INSERT INTO Cities VALUES(null,'Физули');
INSERT INTO Cities VALUES(null,'Ханкенди');
INSERT INTO Cities VALUES(null,'Хачмаз');
INSERT INTO Cities VALUES(null,'Ходжавенд');
INSERT INTO Cities VALUES(null,'Ходжалы');
INSERT INTO Cities VALUES(null,'Худат');
INSERT INTO Cities VALUES(null,'Хызы');
INSERT INTO Cities VALUES(null,'Хырдалан');
INSERT INTO Cities VALUES(null,'Шабран');
INSERT INTO Cities VALUES(null,'Шамкир');
INSERT INTO Cities VALUES(null,'Шарур');
INSERT INTO Cities VALUES(null,'Шахбуз');
INSERT INTO Cities VALUES(null,'Шеки');
INSERT INTO Cities VALUES(null,'Шемахы (Шемаха)');
INSERT INTO Cities VALUES(null,'Ширван');
INSERT INTO Cities VALUES(null,'Шуша');
INSERT INTO Cities VALUES(null,'Ярдымлы');