INSERT INTO Countries VALUES(null,'Казахстан');
INSERT INTO Countries VALUES(null,'Россия');
INSERT INTO Countries VALUES(null,'Азербайджан');
INSERT INTO Countries VALUES(null,'Армения');
INSERT INTO Countries VALUES(null,'Беларусь');
INSERT INTO Countries VALUES(null,'Кыргызстан');
INSERT INTO Countries VALUES(null,'Молдова');
INSERT INTO Countries VALUES(null,'Таджикистан');
INSERT INTO Countries VALUES(null,'Туркменистан');
INSERT INTO Countries VALUES(null,'Узбекистан');
INSERT INTO Countries VALUES(null,'Украина');
-- and so on