INSERT INTO Cities VALUES(null,'Агдам',3);
INSERT INTO Cities VALUES(null,'Агдере',3);
INSERT INTO Cities VALUES(null,'Агдаш',3);
INSERT INTO Cities VALUES(null,'Агджабеди',3);
INSERT INTO Cities VALUES(null,'Аджигабул',3);
INSERT INTO Cities VALUES(null,'Агстафа (Акстафа)',3);
INSERT INTO Cities VALUES(null,'Астара',3);
INSERT INTO Cities VALUES(null,'Ахсу',3);
INSERT INTO Cities VALUES(null,'Бабек',3);
INSERT INTO Cities VALUES(null,'Баку',3);
INSERT INTO Cities VALUES(null,'Барда',3);
INSERT INTO Cities VALUES(null,'Бейлаган',3);
INSERT INTO Cities VALUES(null,'Белакен (Белоканы)',3);
INSERT INTO Cities VALUES(null,'Билясувар',3);
INSERT INTO Cities VALUES(null,'Габала',3);
INSERT INTO Cities VALUES(null,'Газах (Казах)',3);
INSERT INTO Cities VALUES(null,'Гах (Кахи)',3);
INSERT INTO Cities VALUES(null,'Гёйчай (Геокчай)',3);
INSERT INTO Cities VALUES(null,'Геранбой',3);
INSERT INTO Cities VALUES(null,'Гёйгёль',3);
INSERT INTO Cities VALUES(null,'Гёйтепе',3);
INSERT INTO Cities VALUES(null,'Гобустан',3);
INSERT INTO Cities VALUES(null,'Говлар',3);
INSERT INTO Cities VALUES(null,'Горадиз',3);
INSERT INTO Cities VALUES(null,'Губа (Куба)',3);
INSERT INTO Cities VALUES(null,'Губадлы (Кубатлы)',3);
INSERT INTO Cities VALUES(null,'Гусар (Кусары)',3);
INSERT INTO Cities VALUES(null,'Гянджа',3);
INSERT INTO Cities VALUES(null,'Далимамедли',3);
INSERT INTO Cities VALUES(null,'Дашкесан',3);
INSERT INTO Cities VALUES(null,'Джалилабад',3);
INSERT INTO Cities VALUES(null,'Джебраил',3);
INSERT INTO Cities VALUES(null,'Джульфа',3);
INSERT INTO Cities VALUES(null,'Евлах',3);
INSERT INTO Cities VALUES(null,'Загатала (Закаталы)',3);
INSERT INTO Cities VALUES(null,'Зангелан',3);
INSERT INTO Cities VALUES(null,'Зердаб',3);
INSERT INTO Cities VALUES(null,'Имишли',3);
INSERT INTO Cities VALUES(null,'Исмаиллы',3);
INSERT INTO Cities VALUES(null,'Кедабек',3);
INSERT INTO Cities VALUES(null,'Кельбаджар',3);
INSERT INTO Cities VALUES(null,'Кюрдамир',3);
INSERT INTO Cities VALUES(null,'Лачин',3);
INSERT INTO Cities VALUES(null,'Ленкорань',3);
INSERT INTO Cities VALUES(null,'Лерик',3);
INSERT INTO Cities VALUES(null,'Лиман',3);
INSERT INTO Cities VALUES(null,'Масаллы',3);
INSERT INTO Cities VALUES(null,'Мингечевир (Мингечаур)',3);
INSERT INTO Cities VALUES(null,'Нафталан',3);
INSERT INTO Cities VALUES(null,'Нахчыван (Нахичевань)',3);
INSERT INTO Cities VALUES(null,'Нефтечала',3);
INSERT INTO Cities VALUES(null,'Огуз',3);
INSERT INTO Cities VALUES(null,'Ордубад',3);
INSERT INTO Cities VALUES(null,'Саатлы',3);
INSERT INTO Cities VALUES(null,'Сабирабад',3);
INSERT INTO Cities VALUES(null,'Сальян (Сальяны)',3);
INSERT INTO Cities VALUES(null,'Самух',3);
INSERT INTO Cities VALUES(null,'Сиазань',3);
INSERT INTO Cities VALUES(null,'Сумгайыт (Сумгаит)',3);
INSERT INTO Cities VALUES(null,'Товуз',3);
INSERT INTO Cities VALUES(null,'Тертер',3);
INSERT INTO Cities VALUES(null,'Уджары',3);
INSERT INTO Cities VALUES(null,'Физули',3);
INSERT INTO Cities VALUES(null,'Ханкенди',3);
INSERT INTO Cities VALUES(null,'Хачмаз',3);
INSERT INTO Cities VALUES(null,'Ходжавенд',3);
INSERT INTO Cities VALUES(null,'Ходжалы',3);
INSERT INTO Cities VALUES(null,'Худат',3);
INSERT INTO Cities VALUES(null,'Хызы',3);
INSERT INTO Cities VALUES(null,'Хырдалан',3);
INSERT INTO Cities VALUES(null,'Шабран',3);
INSERT INTO Cities VALUES(null,'Шамкир',3);
INSERT INTO Cities VALUES(null,'Шарур',3);
INSERT INTO Cities VALUES(null,'Шахбуз',3);
INSERT INTO Cities VALUES(null,'Шеки',3);
INSERT INTO Cities VALUES(null,'Шемахы (Шемаха)',3);
INSERT INTO Cities VALUES(null,'Ширван',3);
INSERT INTO Cities VALUES(null,'Шуша',3);
INSERT INTO Cities VALUES(null,'Ярдымлы',3);